Everything work except partition evolution deletion
org.apache.iceberg.exceptions.ValidationException: Missing required files to delete:
	at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:49)
	at org.apache.iceberg.ManifestFilterManager.validateRequiredDeletes(ManifestFilterManager.java:237)