Python: Parse UUID as binary in PyArrow
It causes to throw a cast exception:
```
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
Input In [1], in <cell line: 7>()
      3 cat = load_catalog('rest')
      5 tbl = cat.load_table('fokko.uuid_partitioned')
----> 7 tbl.scan().to_arrow()

File ~/Desktop/iceberg/python/pyiceberg/table/__init__.py:386, in DataScan.to_arrow(self)
    375 from pyarrow.dataset import dataset
    377 ds = dataset(
    378     source=locations,
    379     filesystem=fs,
   (...)
    383     schema=schema_to_pyarrow(self.table.schema()),
    384 )
--> 386 return ds.to_table(filter=pyarrow_filter, columns=columns)

File /opt/homebrew/lib/python3.9/site-packages/pyarrow/_dataset.pyx:304, in pyarrow._dataset.Dataset.to_table()

File /opt/homebrew/lib/python3.9/site-packages/pyarrow/_dataset.pyx:2549, in pyarrow._dataset.Scanner.to_table()

File /opt/homebrew/lib/python3.9/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File /opt/homebrew/lib/python3.9/site-packages/pyarrow/error.pxi:121, in pyarrow.lib.check_status()

ArrowNotImplementedError: Unsupported cast from fixed_size_binary[16] to extension<pyiceberg.uuid<UuidType>> (no available cast function for target type)
```

I tried to deserialize it into the custom type, but I didn't
get to the buffers. I decided to keep it a fixed[16] because:

- It would be a major performance penalty to move this to Python
- Also downstream have limited support for UUID