Core: Fix flakiness in HadoopFileIOTest
I've been able to reproduce this locally:

```
HadoopFileIOTest > testDeleteFiles() FAILED
    java.lang.NullPointerException
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.apache.iceberg.hadoop.HadoopFileIOTest.testDeleteFiles(HadoopFileIOTest.java:130)

> Task :iceberg-aws:test

> Task :iceberg-core:test

HadoopFileIOTest > testListPrefix() FAILED
    org.opentest4j.AssertionFailedError: expected: <3501> but was: <3511>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:629)
        at org.apache.iceberg.hadoop.HadoopFileIOTest.testListPrefix(HadoopFileIOTest.java:80)
```

* The flakiness in ` testListPrefix()` occurred because the temp directory was reused across tests and so `testListPrefix()` would find more files being created than the test itself actually created. 

* The flakiness with the NPE in `testDeleteFiles()` happens because `createRandomFiles()` uses a parallel stream and occasially returns a collection with a `null` path, meaning that `createRandomFiles()` sometimes returns faster than the files could have been created and added to the result.