Hive: Fix using Date type as partition field
When using date/timestampas a partition field, it will throw IllegalStateException: Not not instance of...

for example:
create table iceberg_test(id int, name string) partitioned by (dt date) stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';

then insert into :
insert into iceberg_test values(1, 'xxx', '2023-01-01');

The exception is as follows:
java.lang.IllegalStateException: Not an instance of java.lang.Integer: 2023-01-01 at org.apache.iceberg.data.GenericRecord.get(GenericRecord.java:123) at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:71) at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:58) at org.apache.iceberg.PartitionKey.partition(PartitionKey.java:104) 

We will need to wrapping the record into an InternalRecordWrapper