Upgrade Flink version 1.19.0 => 1.19.1
If users run a Flink job on Flink 1.19.1 with IcebergSink compiled against
1.19.0, as is the case prior this change, they will get the following exception
on commit:

```
java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.api.connector.sink2.CommittableSummary.<init>(int, int, java.lang.Long, int, int, int)'
    at org.apache.iceberg.flink.sink.IcebergWriteAggregator.prepareSnapshotPreBarrier(IcebergWriteAggregator.java:91)
```

The reason is that from 1.19.0 to 1.19.1, Flink changed the signature of the
constructor for `CommittableSummary` from

```
CommittableSummary(int, int, Long, int, int, int)
```
to
```
CommittableSummary(int, int, long, int, int, int)
```

Note the `Long` to `long` change. Since Flink 1.19.1 is the latest supported
version and 1.19.0 is no longer supported, it is fair to upgrade.