update TestEnvironmentUtil#testEnvironmentSubstitution() so that it can handle both scenarios where the USER env exists or not.
Otherwise, it can fail with ImmutableMap.of("user-test", System.getenv().get("USER")), if the build env doesn't contain USER env variable, which is the case for our internal build env.

 java.lang.NullPointerException: null value in entry: user-test=null
         at org.apache.iceberg.relocated.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
         at org.apache.iceberg.relocated.com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:43)
         at org.apache.iceberg.relocated.com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:81)
         at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap.of(ImmutableMap.java:126)
         at org.apache.iceberg.util.TestEnvironmentUtil.testEnvironmentSubstitution(TestEnvironmentUtil.java:31)