Python: Install PyYaml
Currently it is missing:

```
root@88de3a02961f:/# pip install "git+https://github.com/apache/iceberg.git#subdirectory=python[pyarrow]"^C
root@88de3a02961f:/# pyiceberg
Traceback (most recent call last):
  File "/usr/local/bin/pyiceberg", line 5, in <module>
    from pyiceberg.cli.console import run
  File "/usr/local/lib/python3.9/site-packages/pyiceberg/cli/console.py", line 30, in <module>
    from pyiceberg.catalog import Catalog, load_catalog
  File "/usr/local/lib/python3.9/site-packages/pyiceberg/catalog/__init__.py", line 37, in <module>
    from pyiceberg.utils.config import Config, merge_config
  File "/usr/local/lib/python3.9/site-packages/pyiceberg/utils/config.py", line 21, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```